In [42]:
import numpy as np

In [43]:
sensors_data = np.array([[22.1, 23.5, 24.0, 28.7, 21.9, 30.2],
                         [101, 100, 102, 101, 99, 103],
                          [45, 47, 44, 50, 42, 55]])

print(sensors_data.shape)
sensors_data = sensors_data.T
print(sensors_data.shape)

(3, 6)
(6, 3)


In [44]:
print(sensors_data.shape)
print(sensors_data.ndim)

(6, 3)
2


In [45]:
print(f"temperature : {sensors_data[:,0]}")

temperature : [22.1 23.5 24.  28.7 21.9 30.2]


In [46]:
print(f"pressure : {sensors_data[:,1]}")

pressure : [101. 100. 102. 101.  99. 103.]


In [47]:
temperature_mean = sensors_data[:,0].mean()
print(f"temperature_mean = {temperature_mean:.2f}")

temperature_mean = 25.07


In [48]:
max_humidity = sensors_data[:,2].max()
print(f"Max Humidity = {max_humidity}")

Max Humidity = 55.0


In [49]:
measurement = sensors_data[sensors_data[:,0] > 25]
print(measurement)

[[ 28.7 101.   50. ]
 [ 30.2 103.   55. ]]


In [50]:
offset  = np.array([0.5,-1,2])
calibration_data = sensors_data + offset
print(calibration_data)

[[ 22.6 100.   47. ]
 [ 24.   99.   49. ]
 [ 24.5 101.   46. ]
 [ 29.2 100.   52. ]
 [ 22.4  98.   44. ]
 [ 30.7 102.   57. ]]


In [51]:
arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
